time python3 main_workload.py --benchmark parsec --workload_name swaptions.trace
time python3 main_workload.py --benchmark parsec --workload_name streamcluster.trace
time python3 main_workload.py --benchmark parsec --workload_name ferret.trace
time python3 main_workload.py --benchmark stream --workload_name copy.trace
time python3 main_workload.py --benchmark stream --workload_name add.trace
time python3 main_workload.py --benchmark stream --workload_name scale.trace
time python3 main_workload.py --benchmark stream --workload_name triad.trace
time python3 main_workload.py --benchmark comm --workload_name comm1
time python3 main_workload.py --benchmark comm --workload_name comm2
time python3 main_workload.py --benchmark comm --workload_name comm3
time python3 main_workload.py --benchmark comm --workload_name comm4
time python3 main_workload.py --benchmark comm --workload_name comm5
time python3 main_workload.py --benchmark comm --workload_name comm5
time python3 main_workload.py --benchmark cpu2017 --workload_name 456.hmmer
time python3 main_workload.py --benchmark cpu2017 --workload_name 544.nab
time python3 main_workload.py --benchmark cpu2017 --workload_name 456.hmmer
time python3 main_workload.py --benchmark cpu2017 --workload_name 456.hmmer
time python3 main_workload.py --benchmark cpu2017 --workload_name 456.hmmer