# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: key_value.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fkey_value.proto\x12\x06vizier\x1a\x19google/protobuf/any.proto\"f\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\n\n\x02ns\x18\x04 \x01(\t\x12\x0f\n\x05value\x18\x02 \x01(\tH\x00\x12%\n\x05proto\x18\x03 \x01(\x0b\x32\x14.google.protobuf.AnyH\x00\x42\t\n\x07\x61_valueb\x06proto3')



_KEYVALUE = DESCRIPTOR.message_types_by_name['KeyValue']
KeyValue = _reflection.GeneratedProtocolMessageType('KeyValue', (_message.Message,), {
  'DESCRIPTOR' : _KEYVALUE,
  '__module__' : 'key_value_pb2'
  # @@protoc_insertion_point(class_scope:vizier.KeyValue)
  })
_sym_db.RegisterMessage(KeyValue)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _KEYVALUE._serialized_start=54
  _KEYVALUE._serialized_end=156
# @@protoc_insertion_point(module_scope)
